version: '3.7'

services:

  db:
    build: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: example
      PG_MAJOR: 12
      PG_VERSION: 12.0-2.pgdg100+1
      PGDATA: /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
