INSERT INTO member SELECT 'Y0099', '2017-03-17', 0, 'f';
INSERT INTO member VALUES('S0003', '2017-05-02', 2700, 'f'), ('S0004', '2017-05-14', 1500, 't');
UPDATE member SET score = score + 2000 WHERE login;
SELECT count(*) FROM member WHERE score < 3000;

CREATE TRIGGER sample_trg BEFORE INSERT OR UPDATE OR DELETE TO sample FOR EACH STATEMENT EXECUTE PROCEDURE log_write();
CREATE TRIGGER sample_trg BEFORE INSERT OR UPDATE OR DELETE ON sample EXECUTE PROCEDURE log_write();
CREATE TRIGGER sample_trg BEFORE INSERT OR UPDATE OR DELETE ON sample FOR EACH ROW EXECUTE PROCEDURE log_write();
CREATE TRIGGER sample_trg AFTER INSERT OR UPDATE OR DELETE ON sample FOR EACH STATEMENT EXECUTE PROCEDURE log_write();
CREATE TRIGGER sample_trg BEFORE INSERT,UPDATE,DELETE ON sample FOR EACH STATEMENT EXECUTE PROCEDURE log_write();

ALTER TABLE sample ADD id PRIMARY KEY;
ALTER COLUMN sample(id) ADD PRIMARY KEY;
ALTER TABLE sample(id) ADD PRIMARY KEY;
ALTER COLUMN id SET PRIMARY KEY;
ALTER TABLE sample ADD PRIMARY KEY(id);

DECLARE sample_cursor SCROLL CURSOR WITH HOLD FOR SELECT * FROM sample;
DECLARE sample_cursor NO SCROLL CURSOR WITH HOLD FOR SELECT * FROM sample;
DECLARE sample_cursor NO SCROLL CURSOR FOR SELECT * FROM sample;
DECLARE sample_cursor SCROLL CURSOR WITHOUT HOLD FOR SELECT * FROM sample;
DECLARE sample_cursor INSENSITIVE CURSOR WITHOUT HOLD FOR SELECT * FROM sample;
